// <auto-generated />
using EF_LoadingDemo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_LoadingDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_LoadingDemo.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Royal Villa",
                            price = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Premium Pool Villa",
                            price = 300.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Luxury Pool Villa",
                            price = 500.0
                        });
                });

            modelBuilder.Entity("EF_LoadingDemo.Models.VillaEminity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaEminity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            VillaId = 1,
                            name = "private pool"
                        },
                        new
                        {
                            Id = 2,
                            VillaId = 1,
                            name = "microwave"
                        },
                        new
                        {
                            Id = 3,
                            VillaId = 1,
                            name = "private balcony"
                        },
                        new
                        {
                            Id = 4,
                            VillaId = 2,
                            name = "1 king size bed"
                        },
                        new
                        {
                            Id = 5,
                            VillaId = 2,
                            name = "pool"
                        },
                        new
                        {
                            Id = 6,
                            VillaId = 3,
                            name = "food + Bed"
                        });
                });

            modelBuilder.Entity("EF_LoadingDemo.Models.VillaEminity", b =>
                {
                    b.HasOne("EF_LoadingDemo.Models.Villa", "Villa")
                        .WithMany("eminity")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("EF_LoadingDemo.Models.Villa", b =>
                {
                    b.Navigation("eminity");
                });
#pragma warning restore 612, 618
        }
    }
}
